title = "Braille Écran"
#baseURL = "https://amazing-clarke-936762.netlify.com/"
baseURL = "https://fabrizziosoares.me/brailleecran"
languageCode = "pt"
theme = "now-ui"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  logo = "images/brailleecran-logo-branco.png"

  [social]
    facebook = ""
    twitter = "https://twitter.com/theleuzera"
    instagram = "https://instagram.com/leuzera___"
    youtube = ""
    github = "https://github.com/leuzera"
    gitlab = ""
    linkedin = "https://www.linkedin.com/in/leuzera/"
    skype = "leonardo.fleury"

[menu]
  [[menu.landing_page]]
    name = "Inicio"
    url = "#header"
    weight = 1
  [[menu.landing_page]]
    name = "Sobre"
    url = "#text"
    weight = 2
  [[menu.landing_page]]
    name = "Time"
    url = "#team"
    weight = 3
  [[menu.landing_page]]
    name = "Noticias"
    url = "#last-posts"
    weight = 4
  [[menu.landing_page]]
    name = "Contato"
    url = "#contact-us"
    weight = 5
  [[menu.landing_page]]
    name = "Download"
    url = "#"
    weight = 6
