title = "Braille Écran"
#baseURL = "https://amazing-clarke-936762.netlify.com/"
baseURL = "https://brailleecran.netlify.com"
languageCode = "pt"
theme = "now-ui"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.pt]
    languageName = "Português"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2
    [languages.en.menu]
  [[languages.en.menu.landing_page]]
    name = "Home"
    url = "#header"
    weight = 1

  [[languages.en.menu.landing_page]]
    name = "About Us"
    url = "#text"
    weight = 2

  [[languages.en.menu.landing_page]]
    name = "Team"
    url = "#team"
    weight = 3

  [[languages.en.menu.landing_page]]
    name = "Posts"
    url = "#last-posts"
    weight = 4

  [[languages.en.menu.landing_page]]
    name = "Contact"
    url = "#contact-us"
    weight = 5


[params]
  logo = "images/brailleecran-logo-branco.png"

  [social]
    facebook = ""
    twitter = "https://twitter.com/theleuzera"
    instagram = "https://instagram.com/leuzera___"
    youtube = ""
    github = "https://github.com/leuzera"
    gitlab = ""
    linkedin = "https://www.linkedin.com/in/leuzera/"
    skype = "leonardo.fleury"

[menu]
  [[menu.landing_page]]
    name = "Inicio"
    url = "#header"
    weight = 1
  [[menu.landing_page]]
    name = "Sobre"
    url = "#text"
    weight = 2
  [[menu.landing_page]]
    name = "Time"
    url = "#team"
    weight = 3
  [[menu.landing_page]]
    name = "Noticias"
    url = "#last-posts"
    weight = 4
  [[menu.landing_page]]
    name = "Contato"
    url = "#contact-us"
    weight = 5
