title = "Braille Écran"
baseURL = "https://amazing-clarke-936762.netlify.com/"
languageCode = "en-us"
theme = "now-ui"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 2 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    weight = 1
  [languages.pt]
    weight = 2
  [languages.es]
    weight = 3

[params]
  logo = "images/brailleecran-logo-branco.png"

  [social]
    facebook = ""
    twitter = "https://twitter.com/theleuzera"
    instagram = "https://instagram.com/leuzera___"
    youtube = ""
    github = "https://github.com/leuzera"
    gitlab = ""
    linkedin = "https://www.linkedin.com/in/leuzera/"
    skype = "leonardo.fleury"