title = "Braille Écran"
baseURL = "https://fabrizziosoares.me/brailleecran"
languageCode = "pt"
theme = "now-ui"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  logo = "images/brailleecran-logo-branco.png"

[menu]
  [[menu.landing_page]]
    name = "Inicio"
    url = "/#header"
    weight = 1
  [[menu.landing_page]]
    name = "Sobre"
    url = "/#text"
    weight = 2
  [[menu.landing_page]]
    name = "Aplicativos"
    url = "/#app-download"
    weight = 3
  [[menu.landing_page]]
    name = "Time"
    url = "/#team"
    weight = 4
  [[menu.landing_page]]
    name = "Contato"
    url = "/#contact-us"
    weight = 5

  [[menu.call_to_action]]
    name = "Acesse os documentos"
    url = "/arquivos"
    weight = 1
