title = "My Personal Site"
baseURL = "http://leuzera.github.io/"
languageCode = "en-us"
theme = "yegor"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  description = "My personal website"
  facebook = ""
  twitter = ""
  instagram = "https://instagram.com/leuzera___"
  youtube = ""
  github = "https://github.com/leuzera"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/leuzera/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  featured_image = "/images/rawpixel-679094-unsplash.jpg"
  recent_posts_number = 5
