[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.52"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b https://amazing-clarke-936762.netlify.com/"

[context.deploy-preview.environment]
HUGO_VERSION = "0.52"